version: '3.4'
services:
  jira-software:
    build: .
    image: ragedunicorn/jira-software:1.0.1-stable
    volumes:
      - jira_home:/var/atlassian/jira
      - jira_logs:/opt/atlassian/jira/logs
    depends_on:
      - postgresql
    networks:
      - jira-software
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.jira-software.environment: "prod"
      com.ragedunicorn.jira-software.description: "JIRA Core"
  postgresql:
    image: ragedunicorn/postgresql:1.0.3-stable
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - jira-software
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  jira_home: {}
  jira_logs: {}
  postgresql_data: {}
networks:
  jira-software:
    driver: bridge
