version: '3.7'
services:
  jira-software:
    image: ragedunicorn/jira-software:1.3.0-stable
    volumes:
      - jira_home:/var/atlassian/jira
      - jira_logs:/opt/atlassian/jira/logs
    environment:
      POSTGRESQL_DATABASE_HOSTNAME: "postgresql"
      JIRA_DATABASE_NAME: "jira"
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.jira-software.environment: "prod"
      com.ragedunicorn.jira-software.description: "JIRA Software"
  postgresql:
    image: ragedunicorn/postgresql:1.2.0-stable
    volumes:
      - postgresql_data:/var/lib/postgresql
    secrets:
      - com.ragedunicorn.postgresql.app_user
      - com.ragedunicorn.postgresql.app_user_password
    healthcheck:
      test: ["CMD", "/docker-healthcheck.sh"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 1m
    labels:
      com.ragedunicorn.postgresql.environment: "prod"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  jira_home: {}
  jira_logs: {}
  postgresql_data: {}
secrets:
  com.ragedunicorn.postgresql.app_user:
    external: true
  com.ragedunicorn.postgresql.app_user_password:
    external: true
