version: '3.7'
services:
  jira-software:
    build: .
    image: ragedunicorn/jira-software:${JIRA_TAG_VERSION}-dev
    volumes:
      - jira_home:/var/atlassian/jira
      - jira_logs:/opt/atlassian/jira/logs
    environment:
      POSTGRESQL_APP_USER: "app"
      POSTGRESQL_APP_PASSWORD: "app"
      POSTGRESQL_DATABASE_HOSTNAME: "postgresql"
      JIRA_DATABASE_NAME: "jira"
    depends_on:
      - postgresql
    networks:
      - jira-software
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.jira-software.environment: "dev"
      com.ragedunicorn.jira-software.description: "JIRA Core"
  postgresql:
    image: ragedunicorn/postgresql:${POSTGRESQL_TAG_VERSION}-dev
    volumes:
      - postgresql_data:/var/lib/postgresql
    environment:
      POSTGRESQL_APP_USER: "app"
      POSTGRESQL_APP_PASSWORD: "app"
    networks:
      - jira-software
    expose:
      - "5432"
    stdin_open: true
    tty: true
    entrypoint: /bin/sh
    labels:
      com.ragedunicorn.postgresql.environment: "dev"
      com.ragedunicorn.postgresql.description: "PostgreSQL"
volumes:
  jira_home: {}
  jira_logs: {}
  postgresql_data: {}
networks:
  jira-software:
    driver: bridge
